version: '3'
services:
  node:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    #depends_on:
    #  - mongo
    volumes:
    - ./src:/usr/app/
    - /usr/app/node_modules

  # Local mongo
  #mongo:
  #  image: mongo:latest
  #  environment:
  #    - MONGO_INITDB_ROOT_USERNAME=root
  #    - MONGO_INITDB_ROOT_PASSWORD=password
  #  volumes:
  #    - mongo-data:/data/db

#volumes:
  #Local mongo
  #mongo-data: